### ISSUE TITLE
Making a cross-compiler for a custom kernel

### ISSUE THREAD

**Issue by AravK** [PowerNex/PowerNex#74]
I'm making a custom kernel and I was wondering how the cross compilers for D were made. Is there any way I could do one for mine? How?

**Comment by Vild** [comment]
This is the CC I use for PowerNex:
https://github.com/PowerNex/powernex-binutils - Patches for compiling gas (gnu assembler) and ld (the linker)
https://github.com/PowerNex/powernex-dmd - Patches for a version of dmd that exports the PowerNex version instead of Linux.

Everything about PowerNex is located in the PowerNex organization (https://github.com/PowerNex).
So everything you need to know should be found there.
