### ISSUE TITLE
SUGGEST: CMake as build system

### ISSUE THREAD

**Issue by AravK** [PowerNex/PowerNex#75]
CMake is a little hard to set up at first, but it gets easier as it goes. CMake keeps it simple and efficient at the same time. You can use [cmake-d](https://github.com/dcarp/cmake-d) for D support in CMake. Toolchain tutorials already exist. You can add the local toolchain directly as paths in the toolchain file.

**Comment by Vild** [comment]
Personally I don't like cmake, IMO it makes everything much harder. It would also add extra unnecessary, big, software that would need to be ported for when I want to become selfhosted.
The current buildsystem, [reggae](https://github.com/atilaneves/reggae), is basically just D code that either gets compiled into a binary or a build.ninja, which I currently use.
I have been working on a custom buildsystem ([Wild](https://github.com/Vild/Wild)), but as I prioritize PowerNex and school projects I have been forced to put that project on hold.

I even go as far as maintain both .vcxproj and a reggafile.d (or in some cases a Makefile) in other projects ([Hydra](https://github.com/HydraInteractive/Hydra)). Because I find this easier than having to fight cmake, which I have done a lot.
