### ISSUE TITLE
[BUG+FIX] ToolchainManager.d has an environmental assumption

### ISSUE THREAD

**Issue by AravK** [PowerNex/PowerNex#79]
I work from a Dev-mode Chromebook, where all my tools are installed in `/usr/local`. `toolchainManager.d` assumes that `/usr/bin/env` is working, but mine is broken.
Instead, I suggest prepending the contents of `toolchainManager.d` with a small Bash script that checks for requirements (`rdmd` exists, recent version, etc.) and then runs `rdmd` with the contents of the rest of the file, then exits.
I have seen this technique used with self-extracting `tar.gz`s.
See [this Stackoverflow Question](https://stackoverflow.com/questions/20758981/self-extracting-script-in-sh-shell), particularly [this answer](https://stackoverflow.com/a/20760267). We just have to replace `tar` with `rdmd`.
This may be a little too Bash-dependent, but using Cygwin would solve that on Windows.

**Comment by Vild** [comment]
I don't know if I would call this a bug just because, as you said, your `/usr/bin/env` is broken.
I would recommend you that you should run `rdmd toolchainmanager.d`, sure I understand that this might not be the best wait of fixing it,
but I expect that the host system that will compile PowerNex is working and is not broken, and thus that `/usr/bin/env` is working correctly.
